const newProductsData = [
  {
    name: "luxury chair",
    price: 220,
    company: "marcos",
    featured: true,
    rating: 4.2,
  },
  {
    name: "comfort sofa",
    price: 350,
    company: "liddy",
    featured: true,
    rating: 4.7,
  },
  {
    name: "modern table",
    price: 180,
    company: "ikea",
    featured: true,
    rating: 4.3,
  },
  {
    name: "classic armchair",
    price: 115,
    company: "caressa",
    rating: 4.1,
  },
  {
    name: "sleek bookshelf",
    price: 60,
    company: "ikea",
    rating: 4.6,
  },
  {
    name: "bar chair",
    price: 85,
    company: "marcos",
    rating: 4.8,
  },
  {
    name: "executive desk",
    price: 295,
    company: "caressa",
    featured: true,
    rating: 4.9,
  },
  {
    name: "recliner sofa",
    price: 450,
    company: "liddy",
    rating: 4.4,
  },
  {
    name: "glass coffee table",
    price: 135,
    company: "ikea",
    rating: 4.7,
  },
  {
    name: "rustic dining set",
    price: 320,
    company: "caressa",
    rating: 4.5,
  },
  {
    name: "leather recliner",
    price: 190,
    company: "marcos",
    rating: 4.9,
  },
  {
    name: "modular sectional",
    price: 400,
    company: "liddy",
    featured: true,
    rating: 4.6,
  },
  {
    name: "queen bed frame",
    price: 210,
    company: "ikea",
    rating: 4.2,
  },
  {
    name: "office chair",
    price: 95,
    company: "caressa",
    rating: 4.0,
  },
  {
    name: "outdoor bench",
    price: 145,
    company: "marcos",
    featured: true,
    rating: 4.3,
  },
  {
    name: "folding table",
    price: 60,
    company: "liddy",
    featured: true,
    rating: 3.9,
  },
  {
    name: "kids bookshelf",
    price: 45,
    company: "ikea",
    rating: 4.1,
  },
  {
    name: "patio chair",
    price: 75,
    company: "caressa",
    featured: true,
    rating: 4.6,
  },
  {
    name: "lounge chair",
    price: 125,
    company: "marcos",
    rating: 4.8,
  },
  {
    name: "corner sectional",
    price: 350,
    company: "liddy",
    rating: 4.7,
  },
  {
    name: "vintage dresser",
    price: 230,
    company: "caressa",
    rating: 4.3,
  },
  {
    name: "glass dining table",
    price: 295,
    company: "ikea",
    rating: 4.7,
  },
  {
    name: "wooden bench",
    price: 130,
    company: "marcos",
    featured: true,
    rating: 4.4,
  },
  {
    name: "adjustable stool",
    price: 75,
    company: "liddy",
    rating: 4.1,
  },
  {
    name: "daybed",
    price: 180,
    company: "caressa",
    rating: 4.2,
  },
  {
    name: "small side table",
    price: 45,
    company: "ikea",
    rating: 4.5,
  },
  {
    name: "executive chair",
    price: 200,
    company: "marcos",
    featured: true,
    rating: 4.9,
  },
  {
    name: "rocking chair",
    price: 80,
    company: "liddy",
    rating: 4.6,
  },
  {
    name: "ottoman stool",
    price: 95,
    company: "caressa",
    featured: true,
    rating: 4.0,
  },
  {
    name: "minimalist desk",
    price: 120,
    company: "ikea",
    rating: 4.3,
  },
  {
    name: "contemporary table",
    price: 160,
    company: "marcos",
    featured: true,
    rating: 4.2,
  },
  {
    name: "traditional sofa",
    price: 350,
    company: "liddy",
    rating: 4.7,
  },
  {
    name: "glass cabinet",
    price: 180,
    company: "caressa",
    rating: 4.4,
  },
  {
    name: "wooden coffee table",
    price: 100,
    company: "ikea",
    featured: true,
    rating: 4.1,
  },
  {
    name: "leather armchair",
    price: 190,
    company: "marcos",
    rating: 4.6,
  },
  {
    name: "round dining table",
    price: 245,
    company: "liddy",
    rating: 4.8,
  },
  {
    name: "kid's chair",
    price: 40,
    company: "caressa",
    featured: true,
    rating: 4.0,
  },
  {
    name: "portable desk",
    price: 85,
    company: "ikea",
    rating: 4.4,
  },
  {
    name: "tall bookshelf",
    price: 160,
    company: "marcos",
    rating: 4.5,
  },
  {
    name: "sofa bed",
    price: 295,
    company: "liddy",
    rating: 4.3,
  },
  {
    name: "reclining chair",
    price: 220,
    company: "caressa",
    rating: 4.7,
  },
  {
    name: "side table",
    price: 50,
    company: "ikea",
    featured: true,
    rating: 4.1,
  },
  {
    name: "accent bench",
    price: 130,
    company: "marcos",
    rating: 4.9,
  },
  {
    name: "wooden sideboard",
    price: 220,
    company: "caressa",
    rating: 4.4,
  },
  {
    name: "plush chair",
    price: 150,
    company: "liddy",
    rating: 4.5,
  },
  {
    name: "garden table",
    price: 170,
    company: "ikea",
    rating: 4.2,
  },
  {
    name: "vintage nightstand",
    price: 95,
    company: "marcos",
    featured: true,
    rating: 4.1,
  },
  {
    name: "kids bunk bed",
    price: 295,
    company: "caressa",
    rating: 4.3,
  },
];

module.exports = newProductsData;
